---
title: "Blog"
---

Jeff Leek’s book How to be a Modern Scientist was designated reading in my statistics course this semester, which has been including aspects beyond the meaty portion of the class on the R language and statistics, but also aspects on how to be an accurate and successful professional in whatever field we end up in as students. This is exactly what the book was about, as it was a primer on more of a “how” to publish and the nitty‐gritty of being a scientist in the “modern” world. It covered topics such as how to write a paper, data sharing, scientific blogging, scientific talks, and how to read scientific papers when we are increasingly becoming time poor.

In this post, I thought I would talk about two aspects that really stuck out to me, which was about scientific bloggings and researching scientific papers. To give some background, I have not published any papers nor have one in the works currently. However, I will be entering a position in May in which I do hope to write a paper, so this book couldn’t have been more timely. I also understand that I am entering an economy that is fragile, and while community organizing is one way to build strength, I also need to individualize and show my skills through regularly cultivating an online presence. As someone who is often leary of online platforms stealing personal data and capitalizing off of faux community online, I tend to stay away (this is why I don’t have a LinkedIn—yet).

To start with, scientific blogging: while I had heard about people using X (formerly Twitter) to publicize their work, I had slowly been noticing something that Jeff Leeks hit straight on the nail, which was that a blog will help raise your profile. This could now be interpreted, as it was written in 2016, as a GitHub (like on this page), a Substack, a WordPress, or any other written text format that allows you to upload your own thoughts to a page about your professional field. In addition to the wording, Leeks comments that it is there incumbent for you to show off your storytelling/communication skills, show what data visualization skills you have, teach others how to do analysis—especially in a world of democratizing knowledge—why not be the one who knows how to teach it easily/better to show your deep understanding and discuss the important topics of your industry? The popular adage is that “to teach you learn twice,” and you are showing off that skill on your page. It is also more popular to include a page to your work on your CV so that, beyond the page, future employers or granters can see a better breadth of your work in the digital age.

The second thing was how to choose which scientific papers to read. I had always known that the big journals such as Nature, PNAS, and Science were well regarded. I didn’t know, as Jeff Leeks puts in his book, that it is important to read these with a healthy grain of salt, to read between the lines, and to really look closely at these papers. While they may and usually are breakthroughs, sometimes they aren’t, and it’s important to develop that critical eye. Another was the way to determine if reading that particular article is interesting for you: first you read the abstract, then the results. If it still interests you, then read it; otherwise, move on. As someone who often feels obliged to read the entire article and sometimes stops halfway, this vindicated me that it just isn’t how I want to spend my time, and that is okay. Only about 1–3% of the time will you read the entire article.

Overall, I found How to be a Modern Scientist useful, straight to the point, slightly outdated, but so helpful in setting up a better understanding of how to navigate the field of modern science without it being quite so daunting.
